= Первые 5 минут устранения неполадок на сервере
:author: Ivan Pesin
:revnumber: 1.1
:revdate: 2013-07-13
:toc: macro
:toc-title: Содержание
:sectanchors:
:icons: font
:source-highlighter: rouge
// :stylesdir: ./stylesheets
:stylesheet: asciidoc-ip.css
:linkcss:

:TODO: pass:q[<span style="background-color: gold">&nbsp; *TODO* </span>:]

First 5 Minutes Troubleshooting A Server by Vincent Viallet, 6 March 2013 +
Original post: http://devo.ps/blog/2013/03/06/troubleshooting-5minutes-on-a-yet-unknown-box.html

Автор: Винсент Виалле +
Translated by Ivan Pesin, July 2013

toc::[]

Когда наша команда еще занималась вопросами эксплуатации, оптимизации и масштабирования в 
http://wiredcraft.com/[предыдущей компании], нам приходилось иметь дело с отладкой медленно работающих приложений и целых инфраструктур, часто большого размера (представьте CNN или the World Bank). Горящие сроки, экзотические стеки технологий и недостаток информации обычно гарантировали незабываемые впечатления.

Причины неполадок редко были очевидными; ниже я привожу список шагов, с которых мы обычно начинали поиск проблемы.

== Войдите немного в контекст

Не спешите бросаться на сервера, сперва нужно выяснить, что уже известно о системе и специфике проблемы. Не стоит тратить время на поиск проблемы вслепую.

Несколько обязательных вопросов, требующих ответа:

- Какие конкретно наблюдаются симптомы? Подвисания? Ошибки?
- Когда проблема была замечена впервые?
- Воспроизводится ли она?
- Есть ли закономерность (например, происходит каждый час)?
- Какие были последние изменения в системе (код, сервисы, стек приложений)?
- Влияет ли проблема на определенную группу пользователей (авторизированных, не авторизированных, с общим географическим расположением...)?
- Имеется ли документация на архитектуру (физическую и логическую)?
- Используется ли система мониторинга? Munin, Zabbix, Nagios, New Relic... Подойдет любая.
- Ведется ли (централизированное) журналирование? Loggly, Airbrake, Graylog...

Последние два пункта представляют собой наиболее удобные источники информации, но не возлагайте на них больших надежд: как ни печально, именно мониторинг и журналирование часто отсутствуют. Если не повезло, сделайте заметку, что это нужно поправить, и двигайтесь дальше.

== Кто здесь?

[source,console]
----
$ w
$ last
----

Не критично, но обычно не стоит заниматься устранением неполадок в системе, в то время когда с ней играются другие люди. На кухне достаточно одного повара.

== Что делали в системе?

[source,console]
----
$ history
----

Всегда полезно посмотреть на историю команд в комбинации с информацией о том, кто ранее заходил в систему. Не забывайте про ответственность: то, что вы администратор, не дает вам права нарушать чужую конфиденциальность.

Маленькая заметка в уме на потом: можно задать переменную окружения `HISTTIMEFORMAT`, чтобы была возможность отслеживать время, когда выполнялись команды из истории. Нет ничего более раздражающего, чем анализ устаревшего списка команд, не имеющих отношения к проблеме...

== Что запущено?

[source,console]
----
$ pstree -a
$ ps aux
----

Вывод `ps aux` содeржит, как правило, много подробной информации о процессах, тогда как `pstree -a` выводит наглядную и лаконичную картину запущенных процессов, вместе с родительской иерархией.
